language: php
sudo: required
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install -y libcurl3 libcurl3-dev php5-curl
  - composer install
script:
  - ./vendor/bin/phpunit tests
